name: open_fashion
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  # ------------------- Dependencies ---------------
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  ionicons: ^0.2.2
  flutter_credit_card: ^4.1.0
  shimmer: ^3.0.0

  # State Management
  provider: ^6.1.5+1

  # Routing
  go_router: ^17.0.1

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # HTTP & Serialization
  http: ^1.6.0
  dio: ^5.4.0 # Better than http for complex APIs

  # Utilities
  intl: ^0.19.0 # Date formatting

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/texts/

  fonts:
    - family: "TenorSans"
      fonts:
        - asset: assets/fonts/Tenor_Sans/TenorSans-Regular.ttf
